services:
  mongo_db:
    container_name: dealership_mongo
    image: mongo:7
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  api:
    container_name: dealership_api
    build: .
    image: dealership-node-api
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    restart: unless-stopped

volumes:
  mongo_data: {}
